id = "macaulay2"
name = "Macaulay2"
version = "0.1.0"
schema_version = 1
authors = ["Doug Torrance <douglas.a.torrance@gmail.com>"]
description = "Macaulay2 language support for Zed"
repository = "https://github.com/d-torrance/zed-macaulay2"

[grammars.macaulay2]
repository = "https://github.com/AlexanderGolys/tree-sitter-macaulay2"
rev = "0ff4cc24387327a40ddec7321792bd81d9bc3565"

[language_servers.m2-language-server]
name = "Macaulay2 Language Server"
languages = ["Macaulay2"]
