id = "macaulay2"
name = "Macaulay2"
version = "0.1.0"
schema_version = 1
authors = ["Doug Torrance <dtorrance9@gatech.edu>"]
description = "Macaulay2 language support for Zed"
repository = "https://github.com/d-torrance/zed-macaulay2"

[grammars.macaulay2]
repository = "https://github.com/AlexanderGolys/tree-sitter-macaulay2"
rev = "95aafb0d1fa66aa5f422ca16af56dd471a15b927"

[language_servers.m2-language-server]
name = "Macaulay2 Language Server"
languages = ["Macaulay2"]
